<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Data_Permohonan extends CI_Controller
{

	public function __construct()
	{
		parent::__construct();

		$this->load->model("M_data_permohonan");
		$this->load->helper('url');
		$this->load->helper('text');
		$this->load->helper('date');
	}

	public function index()
	{
		// Get available jenis perkara for dropdown
		$data['jenis_perkara_list'] = $this->M_data_permohonan->get_jenis_perkara_permohonan();

		// Set default values
		$lap_bulan = $this->input->post('lap_bulan') ?: date('m');
		$lap_tahun = $this->input->post('lap_tahun') ?: date('Y');
		$jenis_perkara = $this->input->post('jenis_perkara') ?: 'Dispensasi Kawin';
		$wilayah = $this->input->post('wilayah') ?: 'Semua';
		$jenis_laporan = $this->input->post('jenis_laporan') ?: 'bulanan';

		// Get data based on report type
		switch ($jenis_laporan) {
			case 'tahunan':
				$data['datafilter'] = $this->M_data_permohonan->data_permohonan_tahunan($lap_tahun, $jenis_perkara, $wilayah);
				break;
			case 'custom':
				$tanggal_mulai = $this->input->post('tanggal_mulai') ?: date('Y-m-01');
				$tanggal_akhir = $this->input->post('tanggal_akhir') ?: date('Y-m-t');
				$data['datafilter'] = $this->M_data_permohonan->data_permohonan_custom($tanggal_mulai, $tanggal_akhir, $jenis_perkara, $wilayah);
				break;
			default: // bulanan
				// Use new method that includes sisa calculations
				$data['datafilter'] = $this->M_data_permohonan->get_sisa_perkara_data($lap_bulan, $lap_tahun, $jenis_perkara, $wilayah, $jenis_laporan);
				break;
		}

		// Get summary statistics
		$data['summary'] = $this->M_data_permohonan->get_summary_statistics($lap_bulan, $lap_tahun, $jenis_perkara, $wilayah, $jenis_laporan);

		// Pass selected values to view
		$data['selected_bulan'] = $lap_bulan;
		$data['selected_tahun'] = $lap_tahun;
		$data['selected_jenis_perkara'] = $jenis_perkara;
		$data['selected_wilayah'] = $wilayah;
		$data['selected_jenis_laporan'] = $jenis_laporan;

		$this->load->view('template/new_header');
		$this->load->view('template/new_sidebar');
		$this->load->view('v_permohonan', $data);
		$this->load->view('template/new_footer');
	}

	public function export_excel()
	{
		$lap_bulan = $this->input->post('lap_bulan') ?: date('m');
		$lap_tahun = $this->input->post('lap_tahun') ?: date('Y');
		$jenis_perkara = $this->input->post('jenis_perkara') ?: 'Dispensasi Kawin';
		$wilayah = $this->input->post('wilayah') ?: 'Semua';
		$jenis_laporan = $this->input->post('jenis_laporan') ?: 'bulanan';

		// Load PHPExcel library
		require_once APPPATH . 'PHPExcel-1.8/Classes/PHPExcel.php';

		$excel = new PHPExcel();
		$excel->getProperties()->setCreator('Laporan PADLI')
			->setLastModifiedBy('System')
			->setTitle('Laporan Data Permohonan Per Wilayah')
			->setSubject('Laporan Data Permohonan')
			->setDescription('Laporan Data Permohonan - Generated by System');

		$excel->setActiveSheetIndex(0);
		$excel->getActiveSheet()->setTitle('Data Permohonan');

		// Set headers
		$headers = ['No', 'Kecamatan', 'Sisa Bulan Lalu', 'Sisa Tahun Lalu', 'Perkara Masuk', 'Perkara Putus', 'Sisa Perkara', 'Persentase Penyelesaian'];

		$col = 'A';
		foreach ($headers as $header) {
			$excel->getActiveSheet()->setCellValue($col . '1', $header);
			$excel->getActiveSheet()->getStyle($col . '1')->getFont()->setBold(true);
			$col++;
		}

		// Get data
		switch ($jenis_laporan) {
			case 'tahunan':
				$data = $this->M_data_permohonan->data_permohonan_tahunan($lap_tahun, $jenis_perkara, $wilayah);
				break;
			case 'custom':
				$tanggal_mulai = $this->input->post('tanggal_mulai') ?: date('Y-m-01');
				$tanggal_akhir = $this->input->post('tanggal_akhir') ?: date('Y-m-t');
				$data = $this->M_data_permohonan->data_permohonan_custom($tanggal_mulai, $tanggal_akhir, $jenis_perkara, $wilayah);
				break;
			default:
				$data = $this->M_data_permohonan->get_sisa_perkara_data($lap_bulan, $lap_tahun, $jenis_perkara, $wilayah, $jenis_laporan);
				break;
		}

		// Fill data
		$row = 2;
		$no = 1;
		foreach ($data as $item) {
			$sisa_bulan_lalu = isset($item->SISA_BULAN_LALU) ? $item->SISA_BULAN_LALU : 0;
			$sisa_tahun_lalu = isset($item->SISA_TAHUN_LALU) ? $item->SISA_TAHUN_LALU : 0;
			$sisa_perkara = $sisa_bulan_lalu + $item->PERKARA_MASUK - $item->PERKARA_PUTUS;
			$total_perkara = $sisa_bulan_lalu + $item->PERKARA_MASUK;

			$excel->getActiveSheet()->setCellValue('A' . $row, $no++);
			$excel->getActiveSheet()->setCellValue('B' . $row, $item->KECAMATAN);
			$excel->getActiveSheet()->setCellValue('C' . $row, $sisa_bulan_lalu);
			$excel->getActiveSheet()->setCellValue('D' . $row, $sisa_tahun_lalu);
			$excel->getActiveSheet()->setCellValue('E' . $row, $item->PERKARA_MASUK);
			$excel->getActiveSheet()->setCellValue('F' . $row, $item->PERKARA_PUTUS);
			$excel->getActiveSheet()->setCellValue('G' . $row, $sisa_perkara);

			// Calculate percentage
			$persentase = ($total_perkara > 0) ? round(($item->PERKARA_PUTUS / $total_perkara) * 100, 2) : 0;
			$excel->getActiveSheet()->setCellValue('H' . $row, $persentase . '%');
			$row++;
		}

		// Auto size columns
		foreach (range('A', 'H') as $columnID) {
			$excel->getActiveSheet()->getColumnDimension($columnID)->setAutoSize(true);
		}

		// Output
		header('Content-Type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename="Laporan_Data_Permohonan_' . date('Y-m-d') . '.xls"');
		header('Cache-Control: max-age=0');

		$objWriter = PHPExcel_IOFactory::createWriter($excel, 'Excel5');
		$objWriter->save('php://output');
	}
}
