CREATE TABLE `perkara` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `jenis_acara` char(1) DEFAULT NULL,
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `tanggal_pendaftaran` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran: isian tanggal',
    `jenis_perkara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `jenis_perkara_kode` varchar(20) DEFAULT '' COMMENT 'Kode Jenis Perkara: merujuk ke tabel jenis_perkara kolom kode (by system)',
    `jenis_perkara_nama` varchar(100) DEFAULT '' COMMENT 'Nama Jenis Perkara: merujuk ke tabel jenis_perkara kolom nama (by system)',
    `jenis_perkara_text` varchar(400) DEFAULT '' COMMENT 'Nama Jenis Perkara lengkap dengan induk perkaranya(by system)',
    `is_rj` int(2) DEFAULT NULL COMMENT 'null: tidak 1:ya 2:tidak',
    `nomor_urut_register` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Buku Register: Reset per bulan',
    `nomor_urut_perkara` int(11) unsigned DEFAULT NULL COMMENT 'Nomor Urut Perkara: reset per tahun untuk tiap alur_perkara_id (manual/by system)',
    `nomor_perkara` varchar(250) NOT NULL COMMENT 'Nomor Perkara: (manual/by system)',
    `nomor_indeks` varchar(250) DEFAULT NULL COMMENT 'Nomor Indeks Perkara: untuk keperluan pengurutan data berdasarkan tahun,alur perkara dan nomor urut perkara (by system)',
    `tanggal_surat` date DEFAULT NULL COMMENT 'Tanggal Surat Gugatan/Permohonan/Pelimpahan: isian tanggal',
    `nomor_surat` varchar(150) DEFAULT '' COMMENT 'Nomor Surat Gugatan/Permohonan/Pelimpahan: isian bebas',
    `surat_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Surat Gugatan/Permohonan/Pelimpahan: form upload',
    `pihak1_text` longtext COMMENT 'Penggugat/Pemohon/Penuntut: (by system)',
    `pengacara_pihak1` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak2_text` longtext COMMENT 'Tergugat/Termohon/Terdakwa: (by system)',
    `pengacara_pihak2` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak3_text` longtext COMMENT 'Pihak Ke Tiga yang melakukan Intervensi: (by system)',
    `pengacara_pihak3` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `pihak4_text` longtext,
    `pengacara_pihak4` longtext COMMENT 'Pengacara Penggugat/Pemohon: isian bebas',
    `para_pihak` longtext,
    `pihak_dipublikasikan` char(1) DEFAULT 'Y' COMMENT 'Para Pihak Dipublikasikan: pilihan(Y=Ya; T=Tidak)',
    `posita` longtext CHARACTER SET utf8mb4,
    `petitum` longtext CHARACTER SET utf8mb4,
    `petitum_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Petitum: form upload',
    `nomor_dakwaan` varchar(150) DEFAULT NULL,
    `tanggal_dakwaan` date DEFAULT NULL,
    `dakwaan` longtext CHARACTER SET utf8mb4,
    `pasal_dakwaan` longtext,
    `dakwaan_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Dakwaan: form upload',
    `tanggal_rencana_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Rencana Perdamaian: isian tanggal',
    `tanggal_pengesahan_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Pengesahan Perdamaian: isian tanggal',
    `tanggal_penyelesaian_mediasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Mediasi: isian tanggal',
    `tanggal_penyelesaian_konsiliasi` date DEFAULT NULL COMMENT 'Tanggal Penyelesaian Konsiliasi: isian tanggal',
    `perkara_rujukan_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara Rujukan: merujuk ke tabel perkara kolom perkara_id',
    `nomor_perkara_rujukan` varchar(50) DEFAULT '' COMMENT 'Nomor Perkara yang menjadi rujukan: merujuk ke tabel perkara kolom nomor_perkara (by system)',
    `tanggal_pendaftaran_rujukan` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran Rujukan: merujuk ke tabel perkara kolom tanggal_pendaftaran (by system)',
    `catatan_pendaftaran` text COMMENT 'Catatan Pendaftaran: isian bebas',
    `prodeo` tinyint(1) DEFAULT '0' COMMENT 'Status Prodeo: 0=Tidak,1:Ya',
    `terdakwa_anak` tinyint(1) DEFAULT '0' COMMENT 'Terdakwa Anak-Anak: 0 Tidak 1=Ya',
    `tahapan_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tahapan Proses: merujuk ke tabel tahapan_proses kolom id (by system)',
    `tahapan_terakhir_text` varchar(50) DEFAULT '' COMMENT 'Nama Tahapan Terakhir: merujuk ke tabel tahapan_proses kolom nama (by system)',
    `proses_terakhir_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Proses Perkara Terakhir: menujuk ke tabel proses kolom id (by system)',
    `proses_terakhir_text` varchar(200) DEFAULT '' COMMENT 'Proses Perkara Terakhir: menujuk ke tabel proses kolom Nama(by system)',
    `nilai_sengketa` bigint(20) unsigned DEFAULT '0',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    UNIQUE KEY `nomor_perkara` (`nomor_perkara`),
    KEY `jenis_perkara_id` (`jenis_perkara_id`),
    KEY `nomor_indeks` (`nomor_indeks`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `tanggal_pendaftaran` (`tanggal_pendaftaran`),
    KEY `tahapan_terakhir_id` (`tahapan_terakhir_id`),
    KEY `proses_terakhir_id` (`proses_terakhir_id`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    KEY `is_rj` (`is_rj`),
    CONSTRAINT `perkara_fk` FOREIGN KEY (`alur_perkara_id`) REFERENCES `alur_perkara` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Induk Perkara'

CREATE TABLE `perkara_banding` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara(by system)',
    `jenis_banding` char(1) NOT NULL DEFAULT '1' COMMENT '1:akhir;2:sela',
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `nomor_perkara_pn` varchar(250) NOT NULL COMMENT 'Nomor Perkara PN: merujuk ke tabel perkara nomor_perkara (by system)',
    `putusan_pn` date DEFAULT NULL COMMENT 'Tanggal Putusan PN/Putusan Verzet',
    `pihak_pembanding` bigint(20) DEFAULT NULL COMMENT 'Pihak Pemohon Banding: pilihan 0=Kedua pihak,1=Penggugat, 2=Tergugat,3=Intervensi\r\n4=pihak1 & 2,5= pihak 2 & 1',
    `permohonan_banding` date DEFAULT NULL COMMENT 'Tanggal Permohonan Banding: isian tanggal(by system)',
    `pemohon_banding` longtext COMMENT 'Pemohon Banding',
    `para_pihak` longtext COMMENT 'Para Pihak: (by system)',
    `pemberitahuan_putusan_pn` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan PN Ke Pemohon Banding Merujuk Ke Tabel perkara_putusan kolom permberiatahuan_putusan (by system)',
    `pemberitahuan_permohonan_banding` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Permohonan Banding: isian tanggal',
    `penerimaan_memori_banding` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Memori Banding: isian tanggal',
    `penyerahan_memori_banding` date DEFAULT NULL COMMENT 'Tanggal Penyerahan Memori Banding: isian tanggal',
    `penerimaan_kontra_banding` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Kontra Banding: isian tanggal',
    `penyerahan_kontra_banding` date DEFAULT NULL COMMENT 'Tanggal Penyerahan Kontra Banding: isian tanggal',
    `pemberitahuan_inzage` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Inzage Pembanding: isian tanggal',
    `pemberitahuan_inzage_pembanding` date DEFAULT NULL,
    `pemberitahuan_inzage_terbanding` date DEFAULT NULL,
    `pelaksanaan_inzage` date DEFAULT NULL COMMENT 'Tanggal Pelaksanaan Inzage: isian tanggal',
    `pelaksanaan_inzage_pembanding` date DEFAULT NULL,
    `pelaksanaan_inzage_terbanding` date DEFAULT NULL,
    `pengiriman_berkas_banding` date DEFAULT NULL COMMENT 'Tanggal Pengiriman Berkas Dari PN ke PT: isian tanggal',
    `nomor_surat_pengiriman_berkas_banding` varchar(255) DEFAULT '' COMMENT 'Nomor Surat Pengiriman Berkas Dari PN ke PT: isian bebas',
    `surat_pengantar_path` varchar(500) DEFAULT NULL,
    `tanggal_kirim` datetime DEFAULT NULL,
    `penerimaan_kembali_berkas_banding` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Berkas Dari PT Ke PN: isian tanggal',
    `nomor_urut_register` int(11) DEFAULT NULL COMMENT 'nomor urut register banding',
    `tanggal_pendaftaran_banding` date DEFAULT NULL COMMENT 'Tgl Pendaftaran Perkara PT',
    `nomor_perkara_banding` varchar(50) DEFAULT '' COMMENT 'Nomor Perkara PT',
    `panitera_pembuat_akta_banding` bigint(20) unsigned DEFAULT NULL COMMENT 'refer ke panitera_pn',
    `hakim1_banding_id` bigint(20) DEFAULT NULL,
    `hakim1_banding` varchar(255) DEFAULT '' COMMENT 'Nama Hakim 1 Tingkat Banding: merujuk ke tabel hakim_pt kolom nama',
    `hakim2_banding_id` bigint(20) DEFAULT NULL,
    `hakim2_banding` varchar(255) DEFAULT '' COMMENT 'Nama Hakim 2 Tingkat Banding: merujuk ke tabel hakim_pt kolom nama',
    `hakim3_banding_id` bigint(20) DEFAULT NULL,
    `hakim3_banding` varchar(255) DEFAULT '' COMMENT 'Nama Hakim 3 Tingkat Banding: merujuk ke tabel hakim_pt kolom nama',
    `hakim4_banding_id` bigint(20) DEFAULT NULL,
    `hakim4_banding` varchar(255) DEFAULT '' COMMENT 'Nama Hakim 4 Tingkat Banding: merujuk ke tabel hakim_pt kolom nama',
    `hakim5_banding_id` bigint(20) DEFAULT NULL,
    `hakim5_banding` varchar(255) DEFAULT '' COMMENT 'Nama Hakim 5 Tingkat Banding: merujuk ke tabel hakim_pt kolom nama',
    `majelis_hakim_banding` varchar(500) DEFAULT '' COMMENT 'Daftar Nama Makelis Hakim Tingkat Banding : dipisahkan dengan <br/ >(by system)',
    `panitera_pengganti_banding_id` bigint(20) DEFAULT NULL,
    `panitera_pengganti_banding` varchar(255) DEFAULT '' COMMENT 'Nama Panitera Pengganti Tingkat Banding: merujuk ke tabel panitera_pt kolom nama',
    `tanggal_penetapan_sidang_pertama` date DEFAULT NULL COMMENT 'tgl penetapan sidang pertama PT',
    `tanggal_sidang_pertama` date DEFAULT NULL COMMENT 'tgl Sidang pertama PT',
    `putusan_banding` date DEFAULT NULL COMMENT 'Tanggal Putusan PT: isian tanggal',
    `sumber_hukum_id` int(11) unsigned DEFAULT NULL COMMENT 'Diputus Dengan: pilihan (KUH Perdata,KUH Dagang, Adat, UU/PP)',
    `status_putusan_banding_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Status Putusan: merujuk ke tabel status_putusan kolom id',
    `status_putusan_banding_text` varchar(50) DEFAULT '' COMMENT 'Nama Status Putusan: merujuk ke tabel status_putusan kolom id (by system)',
    `nomor_putusan_banding` varchar(255) DEFAULT '' COMMENT 'Nomor Putusan PT: isian bebas',
    `amar_putusan_banding` longtext CHARACTER SET utf8mb4,
    `amar_putusan_banding_dok` varchar(250) DEFAULT '' COMMENT 'Link Dokumen Amar Putusan Banding: form upload',
    `tgl_kirim_salinan_putusan` date DEFAULT NULL COMMENT 'Tanggal Kiriman Salinan Putusan input di Pengadilan Banding',
    `minutasi_banding` date DEFAULT NULL COMMENT 'Tanggal Minutasi',
    `tgl_minutasi` date DEFAULT NULL COMMENT 'Tanggal Minutasi input di Pengadilan Banding',
    `tgl_pengiriman_berkas_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengiriman Berkas dari Pengadilan Banding Ke Pengadilan Tingkat Pertama',
    `pemberitahuan_putusan_banding` date DEFAULT NULL COMMENT 'Tanggal pemberitahuan Putusan Banding Pada Pemohon/Termohon/Pembanding/Terbanding: isian tanggal',
    `pemberitahuan_putusan_banding_pembanding` date DEFAULT NULL,
    `pemberitahuan_putusan_banding_terbanding` date DEFAULT NULL,
    `tgl_pemberitahuan_putusan` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan input di Pengadilan Banding',
    `catatan_banding` text COMMENT 'Catatan Putusan Banding: isian bebas',
    `prodeo_banding` tinyint(1) DEFAULT '0' COMMENT 'Status Prodeo Banding: 0=Tidak, 1=Ya',
    `status_banding_id` int(11) unsigned DEFAULT NULL COMMENT 'Status_Banding',
    `status_banding_text` varchar(100) DEFAULT '',
    `tanggal_cabut` date DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT '' COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    KEY `nomor_perkara_pn` (`nomor_perkara_pn`),
    KEY `nomor_perkara_banding` (`nomor_perkara_banding`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    CONSTRAINT `perkara_banding_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Perkara Banding'

CREATE TABLE `perkara_banding_detil` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara(by system)',
    `alur_perkara_id` int(11) unsigned NOT NULL,
    `status_pihak_id` int(11) unsigned DEFAULT NULL COMMENT 'Referense status_pihak',
    `status_pihak_text` longtext COMMENT 'Status Pihak: (by system)',
    `urutan_banding` bigint(20) DEFAULT '0',
    `permohonan_banding` date DEFAULT NULL COMMENT 'Tanggal Permohonan Banding: isian tanggal',
    `pihak_asal` bigint(20) DEFAULT NULL COMMENT 'Status Asal Pihak: pilihan(1=Pihak1;2=Pihak2;3=Pihak3)',
    `pihak_asal_text` longtext,
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak Pemohon Banding: dipisahkan dengan koma',
    `pihak_nama` longtext COMMENT 'Nama Pihak Pembanding: (by system)',
    `pihak_diwakili` char(1) DEFAULT NULL COMMENT 'Pembanding Diwakili: pilihan (Y=Ya; T=Tidak)',
    `pemohon_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak Kuasa Pembanding: merujuk ke tabel pihak kolom id',
    `pemohon_nama` longtext COMMENT 'Nama Pembanding: isian bebas',
    `pemohon_pekerjaan` varchar(255) DEFAULT '' COMMENT 'Pekerjaan Kuasa Pembanding: isian bebas',
    `pemohon_alamat` varchar(500) DEFAULT '' COMMENT 'Alamat Kuasa Pembanding: isian bebas',
    `pemohon_tanggal_surat` date DEFAULT NULL COMMENT 'Tanggal Surat Kuasa Pembanding: isian tanggal',
    `pemohon_nomor_surat` varchar(255) DEFAULT '' COMMENT 'Nomor Surat Kuasa: isian bebas',
    `pemohon_banding` longtext COMMENT 'Pemohon Banding: (by system)',
    `pemberitahuan_putusan_pn` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan PN Ke Pemohon Banding Merujuk Ke Tabel perkara_putusan kolom permberiatahuan_putusan (by system)',
    `pemberitahuan_permohonan_banding` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Permohonan Banding: isian tanggal',
    `penerimaan_memori_banding` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Memori Banding: isian tanggal',
    `penyerahan_memori_banding` date DEFAULT NULL COMMENT 'Tanggal Penyerahan Memori Banding: isian tanggal',
    `penerimaan_kontra_banding` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Kontra Banding: isian tanggal',
    `penyerahan_kontra_banding` date DEFAULT NULL COMMENT 'Tanggal Penyerahan Kontra Banding: isian tanggal',
    `pemberitahuan_inzage` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Inzage Pembanding: isian tanggal',
    `pelaksanaan_inzage` date DEFAULT NULL COMMENT 'Tanggal Pelaksanaan Inzage: isian tanggal',
    `pemberitahuan_putusan_banding` date DEFAULT NULL COMMENT 'Tanggal pemberitahuan Putusan Banding Pada Pemohon/Termohon/Pembanding/Terbanding: isian tanggal',
    `tanggal_kirim_salinan_putusan` date DEFAULT NULL,
    `tanggal_cabut` date DEFAULT NULL,
    `dokumen_cabut_pihak` varchar(255) DEFAULT NULL,
    `dokumen_cabut_satker` varchar(255) DEFAULT NULL,
    `keterangan` text COMMENT 'Keterangan: isian bebas',
    `kondisi_pihak` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Apabila Y Pihak Masih Hidup Tapi Kalo T Pihak Wafat',
    `diedit_oleh` varchar(30) DEFAULT '' COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    KEY `pemohon_id` (`pemohon_id`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    CONSTRAINT `perkara_banding_detil_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara_banding` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 80 DEFAULT CHARSET = latin1 COMMENT = 'Data Perkara Banding'

CREATE TABLE `perkara_biaya` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'Primary key: (by system)',
    `id_pembiayaan` tinyint(1) DEFAULT '1' COMMENT '1:reguler;2:Prodeo DIPA;3:Prodeo Murni',
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id (by system)',
    `general_id` bigint(20) DEFAULT '0' COMMENT 'general_id merujuk pada setiap tabel perkara',
    `tahapan_id` int(11) unsigned DEFAULT NULL COMMENT 'Tahapan Proses : merujuk ke tabel tahapan_proses (by system)',
    `kategori_id` int(11) unsigned DEFAULT NULL COMMENT 'Kategori Biaya: merujuk ke tabel kategori_biaya kolom id',
    `jenis_biaya_id` int(11) unsigned DEFAULT NULL COMMENT 'Jenis Biaya: merujuk ke tabel jenis_biaya kolom id',
    `pihak_id` bigint(20) DEFAULT NULL COMMENT 'ID Pihak pembayar',
    `pihak_ke` int(11) DEFAULT NULL COMMENT 'Pihak Pembayar ke (1=Penggugat, 2=Tergugat)',
    `urutan` int(11) unsigned DEFAULT NULL,
    `jenis_transaksi` tinyint(1) NOT NULL COMMENT 'Jenis Transaksi: -1=Pengeluaran; 1=Penerimaan',
    `tanggal_transaksi` date NOT NULL COMMENT 'Tanggal Tansaksi: isian tanggal',
    `uraian` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '' COMMENT 'Uraian Transaksi: isian bebas',
    `jumlah` decimal(16, 2) unsigned NOT NULL COMMENT 'Jumlah nominal tansaksi(dalam Rp)',
    `sisa` decimal(16, 2) unsigned DEFAULT NULL COMMENT 'Jumlah Nominal Sisa: isian bilangan (Rp)',
    `keterangan` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `jenis_biaya_id` (`jenis_biaya_id`),
    KEY `jumlah` (`jumlah`),
    KEY `urutan` (`urutan`),
    KEY `tahapan_id` (`tahapan_id`),
    KEY `kategori_id` (`kategori_id`),
    KEY `tanggal_transaksi` (`tanggal_transaksi`),
    CONSTRAINT `perkara_biaya_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_biaya_fk1` FOREIGN KEY (`jenis_biaya_id`) REFERENCES `jenis_biaya` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Biaya Perkara'

CREATE TABLE `perkara_biaya_jurusita` (
    `perkara_biaya_id` bigint(20) unsigned NOT NULL,
    `jurusita_id` int(11) unsigned NOT NULL,
    PRIMARY KEY (`perkara_biaya_id`),
    KEY `jurusita_id` (`jurusita_id`),
    CONSTRAINT `perkara_biaya_jurusita_ibfk_1` FOREIGN KEY (`perkara_biaya_id`) REFERENCES `perkara_biaya` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_data_dukung_mediasi` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) DEFAULT NULL,
    `mediasi_id` bigint(20) NOT NULL COMMENT 'fk perkara_mediasi',
    `identifier` varchar(30) NOT NULL COMMENT 'varibel template',
    `kode_template` varchar(30) NOT NULL COMMENT 'kode template',
    `uraian` longtext NOT NULL COMMENT 'isi variabel',
    `nilai` int(11) DEFAULT NULL COMMENT 'jika ada',
    PRIMARY KEY (`id`),
    KEY `mediasi_id` (`mediasi_id`),
    CONSTRAINT `perkara_data_dukung_mediasi_ibfk_1` FOREIGN KEY (`mediasi_id`) REFERENCES `perkara_mediasi` (`mediasi_id`) ON DELETE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 1000 DEFAULT CHARSET = latin1

CREATE TABLE `perkara_data_pernikahan` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `tgl_nikah` date NOT NULL,
    `tgl_kutipan_akta_nikah` date NOT NULL,
    `no_kutipan_akta_nikah` varchar(100) DEFAULT NULL,
    `kua_tempat_nikah` varchar(255) DEFAULT NULL,
    `kode_kua` int(11) DEFAULT NULL COMMENT 'merujuk kode_kua ref_kua',
    `diedit_oleh` varchar(30) DEFAULT NULL,
    `diedit_tanggal` datetime DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`),
    CONSTRAINT `perkara_data_pernikahan_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_efiling` (
    `efiling_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `satker_id` int(11) NOT NULL COMMENT 'pengadilan id tempat pendaftaran',
    `juncto_efiling_id` bigint(20) unsigned DEFAULT NULL,
    `kode_satker` varchar(10) DEFAULT NULL COMMENT 'kode satker',
    `nama_satker` varchar(255) DEFAULT NULL COMMENT 'nama pengadilan',
    `user_id` bigint(20) DEFAULT NULL COMMENT 'ID User Kepemilikan',
    `nomor_register` varchar(30) DEFAULT NULL COMMENT 'Nomor Register Pendaftaran Online',
    `tanggal_pendaftaran` date DEFAULT NULL COMMENT 'Tanggal Pendaftaran: isian tanggal',
    `alur_perkara_id` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `jenis_perkara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `jenis_perkara_nama` varchar(100) DEFAULT '' COMMENT 'Nama Jenis Perkara: merujuk ke tabel jenis_perkara kolom nama (by system)',
    `status_pendaftaran_id` int(11) DEFAULT NULL COMMENT 'Merujuk ke ref_status_pendaftaran',
    `status_pendaftaran_text` varchar(255) DEFAULT NULL COMMENT 'Merujuk ke ref_status',
    `nomor_va` char(100) DEFAULT NULL,
    `digit_ran` double DEFAULT NULL COMMENT 'Angka Acak yang ditambahkan',
    `jumlah_skum` double DEFAULT NULL COMMENT 'Nominal Pembayaran',
    `tanggal_bayar` datetime DEFAULT NULL,
    `batas_pembayaran` datetime DEFAULT NULL COMMENT 'Batas Pembayaran',
    `status_pembayaran` char(1) DEFAULT '0' COMMENT '1: Dibayar else: Blm Dibayar',
    `nomor_perkara` varchar(250) DEFAULT NULL COMMENT 'Nomor Perkara setelah di setujui',
    `tgl_pendaftaran_perkara` date DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    `status_litigasi` tinyint(1) DEFAULT NULL,
    `informasi_tambahan` longtext CHARACTER SET utf8mb4,
    PRIMARY KEY (`efiling_id`, `satker_id`),
    KEY `jenis_perkara_id` (`jenis_perkara_id`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `tanggal_pendaftaran` (`tanggal_pendaftaran`),
    KEY `diinput_tanggal` (`diinput_tanggal`),
    KEY `diperbaharui_tanggal` (`diperbaharui_tanggal`),
    KEY `nomor_perkara` (`nomor_perkara`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Induk Perkara'

CREATE TABLE `perkara_efiling_id` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `efiling_id` bigint(20) NOT NULL,
    PRIMARY KEY (`efiling_id`),
    KEY `perkara_id` (`perkara_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_hakim_pn` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key: (by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id (by system)',
    `tahapan_id` tinyint(4) NOT NULL DEFAULT '10' COMMENT 'Mengacu ke Table Tahapan',
    `tanggal_penetapan` date DEFAULT NULL COMMENT 'Tanggal Penetapan: isian tanggal',
    `nomor_sk_penetapan` varchar(50) DEFAULT NULL COMMENT 'Nomor SK Penetapan: isian bebas',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: (by system)',
    `jabatan_hakim_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jabatan Hakim: merujuk ke tabel jabatan_hakim kolom id',
    `jabatan_hakim_nama` varchar(50) DEFAULT NULL COMMENT 'Jabatan Hakim: merujuk ke tabel jabatan_hakim kolom nama (by system)',
    `hakim_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Hakim: merujuk ke tabel hakim_pn kolom id',
    `hakim_kode` varchar(20) DEFAULT NULL COMMENT 'Kode Hakim: merujuk ke tabel hakim_pn kolom kode(by system)',
    `hakim_nip` varchar(20) DEFAULT NULL COMMENT 'NIP Hakim : merujuk ke tabel hakim_pn kolom nip (by system)',
    `hakim_nama` varchar(50) DEFAULT NULL COMMENT 'Nama Hakim: merujuk ke tabel hakim_pn kolom nama (by system)',
    `diganti_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Hakim Pengganti: merujuk ke tabel hakim_pn',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `tanggal_tidak_aktif` date DEFAULT NULL COMMENT 'Tanggal Tidak Aktif: isian tanggal',
    `keterangan` varchar(500) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `jabatan_hakim_id` (`jabatan_hakim_id`),
    KEY `hakim_id` (`hakim_id`),
    KEY `hakim_kode` (`hakim_kode`),
    KEY `hakim_nip` (`hakim_nip`),
    KEY `hakim_nama` (`hakim_nama`),
    KEY `urutan` (`urutan`),
    KEY `aktif` (`aktif`),
    CONSTRAINT `perkara_hakim_pn_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_hakim_pn_fk1` FOREIGN KEY (`jabatan_hakim_id`) REFERENCES `jabatan_hakim` (`id`),
    CONSTRAINT `perkara_hakim_pn_fk2` FOREIGN KEY (`hakim_id`) REFERENCES `hakim_pn` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 36347 DEFAULT CHARSET = latin1 AVG_ROW_LENGTH = 255 COMMENT = 'Data Majelis Hakim di Tingkat Pertama'

CREATE TABLE `perkara_ikrar_talak` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `penetapan_majelis_hakim` date DEFAULT NULL,
    `majelis_hakim_id` varchar(50) DEFAULT NULL,
    `majelis_hakim_nama` varchar(500) DEFAULT NULL,
    `majelis_hakim_text` varchar(500) DEFAULT NULL,
    `penetapan_panitera_pengganti` date DEFAULT NULL,
    `panitera_pengganti_id` varchar(50) DEFAULT NULL,
    `panitera_pengganti_text` varchar(500) DEFAULT NULL,
    `penetapan_jurusita` date DEFAULT NULL,
    `jurusita_id` varchar(50) DEFAULT NULL,
    `jurusita_text` varchar(500) DEFAULT NULL,
    `sidang_id` bigint(20) DEFAULT NULL,
    `tanggal_penetapan_sidang_ikrar` date DEFAULT NULL,
    `tanggal_sidang_pertama` date DEFAULT NULL,
    `tgl_ikrar_talak` date DEFAULT NULL,
    `status_penetapan_ikrar_talak_id` char(1) DEFAULT NULL,
    `amar_ikrar_talak` longtext CHARACTER SET utf8mb4,
    `ikrar_talak_dok` varchar(255) DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`),
    CONSTRAINT `perkara_ikrar_talak_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_izin_cerai` (
    `perkara_id` bigint(20) unsigned NOT NULL,
    `pihak_id` bigint(20) NOT NULL,
    `STATUS` tinyint(1) DEFAULT NULL,
    `tanggal_surat` date DEFAULT NULL,
    `nomor_surat` varchar(30) DEFAULT NULL,
    `nama_pejabat` varchar(50) DEFAULT NULL,
    `jabatan_pejabat` varchar(50) DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT NULL,
    `diedit_tanggal` datetime DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`pihak_id`),
    KEY `perkara_izin_cerai_fk` (`perkara_id`),
    CONSTRAINT `perkara_izin_cerai_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_jadwal_mediasi` (
    `id` bigint(20) unsigned NOT NULL,
    `mediasi_id` bigint(20) NOT NULL,
    `urutan` int(11) unsigned NOT NULL DEFAULT '1',
    `tanggal_mediasi` date NOT NULL,
    `jam_mediasi` time DEFAULT NULL,
    `sampai_jam` time DEFAULT NULL,
    `tempat` varchar(500) DEFAULT NULL,
    `dihadiri_oleh` char(1) DEFAULT NULL COMMENT '1. Semua Pihak, 2.Penggugat Saja, 3.Tergugat Saja, 4.Semua Pihak Tidak Hadir',
    `ditunda` char(1) DEFAULT 'T',
    `diedit_oleh` varchar(30) DEFAULT NULL,
    `diedit_tanggal` datetime DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`mediasi_id`),
    KEY `tanggal_sidang` (`tanggal_mediasi`),
    CONSTRAINT `mediasi_jadwal` FOREIGN KEY (`mediasi_id`) REFERENCES `perkara_mediasi` (`mediasi_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_jadwal_sidang` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'Primary key: (by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id',
    `verzet` char(1) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'T' COMMENT 'flag untuk sidang verzet/biasa (by system)',
    `keberatan` char(1) DEFAULT 'T' COMMENT 'flag untuk sidang perkara keberatan',
    `ikrar_talak` char(1) DEFAULT 'T',
    `urutan` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Urutan Jadwal Sidang Salam Satu Hari yang sama: (by system)',
    `tanggal_sidang` date NOT NULL COMMENT 'Tanggal Sidang: isian tanggal',
    `jam_sidang` time DEFAULT NULL COMMENT 'Mulai Jam Sidang: isian format jam:menit',
    `sampai_jam` time DEFAULT NULL COMMENT 'Sampai Jam Sidang : isian format jam:menit',
    `agenda_id` varchar(50) DEFAULT NULL COMMENT 'Agenda Sidang : merujuk ke tabel agenda_sidang dengan pemisah koma',
    `agenda` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Agenda Sidang: isian bebas',
    `ruangan_id` int(11) unsigned DEFAULT NULL COMMENT 'id Ruangan Sidang: merujuk ke tabel ruangan_sidang kolom id',
    `ruangan` varchar(50) DEFAULT NULL COMMENT 'Ruangan Sidang: merujuk ke tabel ruangan_sidang kolom nama (by system)',
    `sidang_keliling` char(1) DEFAULT 'T' COMMENT 'Y dan T',
    `dihadiri_oleh` tinyint(3) DEFAULT NULL,
    `ditunda` char(1) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'T' COMMENT 'Sidang Ditunda: pilihan Y=Ya; T=Tidak',
    `alasan_ditunda` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Alasan Ditunda: isian bebas',
    `sidang_ditempat` tinyint(1) DEFAULT '0' COMMENT 'Sidang Di Tempat: 0=Tidak, 1=Ya',
    `sifat_sidang` char(1) DEFAULT 'Y' COMMENT 'Y: Dibuka Untuk Umum, T: Tertutup Untuk Umum',
    `keterangan` varchar(500) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `edoc_bas` varchar(250) DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `verzet` (`verzet`),
    KEY `perkara_id` (`perkara_id`),
    KEY `ruangan_id` (`ruangan_id`),
    KEY `tanggal_sidang` (`tanggal_sidang`),
    KEY `jam_sidang` (`jam_sidang`),
    CONSTRAINT `perkara_jadwal_sidang_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_jadwal_sidang_fk1` FOREIGN KEY (`ruangan_id`) REFERENCES `ruangan_sidang` (`id`) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Jadwal Pesidangan'

CREATE TABLE `perkara_jurusita` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (generate by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara merujuk ke tabel perkara',
    `general_id` bigint(20) DEFAULT '0',
    `tahapan_id` tinyint(4) NOT NULL DEFAULT '10' COMMENT 'Mengacu ke Table Tahapan',
    `tanggal_penetapan` date DEFAULT NULL COMMENT 'Tanggal penetapan',
    `nomor_sk_penetapan` varchar(50) DEFAULT '' COMMENT 'Nomor SK Penetapan: isian bebas',
    `urutan` int(11) unsigned DEFAULT '1' COMMENT 'Urutan: by(system)',
    `jurusita_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jurusita: merujuk ke tabel jurusita kolom id',
    `jurusita_kode` varchar(20) DEFAULT '' COMMENT 'Kode Jurusita: merujuk ke tabel jurusitakolom kode (by system)',
    `jurusita_nip` varchar(20) DEFAULT '' COMMENT 'NIP Jurusita: merujuk ke tabel jurusita kolom nip (by system)',
    `jurusita_nama` varchar(50) DEFAULT '' COMMENT 'Nama jurusita: merujuk ke tabel jurusita kolom nama (by system)',
    `diganti_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Jurusita Pengganti: merujuk ke tabel jurusita kolom id',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `tanggal_tidak_aktif` date DEFAULT NULL COMMENT 'Tanggal Tidak Aktif: isian tanggal',
    `keterangan` varchar(500) DEFAULT '' COMMENT 'Keterangan: isian bebas',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `jurusita_id` (`jurusita_id`),
    KEY `jurusita_nama` (`jurusita_nama`),
    KEY `aktif` (`aktif`),
    CONSTRAINT `perkara_jurusita_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_jurusita_fk1` FOREIGN KEY (`jurusita_id`) REFERENCES `jurusita` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Jurusita Perkara'

CREATE TABLE `perkara_kasasi_detil` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key: merujuk ke tabel perkara kolom perkara_id (by system)',
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Alur Perkara: merujuk ke tabel alur_perkara kolom id(by system)',
    `status_pihak_id` int(11) DEFAULT NULL COMMENT 'Status Pihak: 1=Pemohon Kasasi; 2=Termohon Kasasi',
    `status_pihak_text` longtext,
    `urutan_kasasi` bigint(20) DEFAULT NULL,
    `permohonan_kasasi` date DEFAULT NULL COMMENT 'Tanggal Permohonan Kasasi: isian tanggal',
    `pihak_asal` bigint(20) DEFAULT NULL COMMENT 'Status Semula: pilihan 1=pihak1; 2=pihak2',
    `pihak_asal_text` longtext,
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak kolom id',
    `pihak_nama` longtext COMMENT 'Nama Pihak: (by system)',
    `pihak_diwakili` char(1) DEFAULT NULL COMMENT 'Diwakili: Y=Ya; T=Tidak',
    `pemohon_id` bigint(20) DEFAULT NULL COMMENT 'Id Pihak Pemohon',
    `pemohon_nama` longtext COMMENT 'Nama Pemohon Kasasi: isian bebas',
    `pemohon_pekerjaan` varchar(255) DEFAULT NULL COMMENT 'Pekerjaan Pemohon Kasasi: isian bebas',
    `pemohon_alamat` varchar(1000) DEFAULT NULL COMMENT 'Alamat Pemohon Kasasi: by(system)',
    `pemohon_tanggal_surat` date DEFAULT NULL COMMENT 'Tanggal Surat Kuasa: isian tanggal',
    `pemohon_nomor_surat` varchar(50) DEFAULT NULL COMMENT 'Nomor Surat Kuasa: isian bebas',
    `pemohon_kasasi` longtext COMMENT 'Pemohon Kasasi: (by system)',
    `pemberitahuan_putusan_pn` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan PN ke Pemohon: menurjuk ke tabel perkara_putusan kolom pemberitahuan_putusan (by system)',
    `pemberitahuan_putusan_banding` date DEFAULT NULL COMMENT 'Tanggal pemberitahuan putusan PT ke Pemohon: merujuk ke tabel perkara_banding kolom pemberitahuan_putusan_banding (by system)',
    `pemberitahuan_kasasi` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Kasasi: isian tanggal',
    `penerimaan_memori_kasasi` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Memori Kasasi: isian tanggal',
    `penyerahan_memori_kasasi` date DEFAULT NULL COMMENT 'Tanggal Penyerahan Memori Kasasi: isian tanggal',
    `penerimaan_kontra_kasasi` date DEFAULT NULL COMMENT 'Tanggal Penerimaan Kontra Kasasi: isian tanggal',
    `penyerahan_kontra_kasasi` date DEFAULT NULL COMMENT 'Tanggal Penyerahan Kontra Kasasi: isian tanggal',
    `pemberitahuan_inzage_kasasi` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Inzage Kasasi: isian tanggal',
    `pelaksanaan_inzage_kasasi` date DEFAULT NULL COMMENT 'Tanggal Pelaksanaan Inzage Kasasi: isian tanggal',
    `pemberitahuan_putusan_kasasi` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan putusan Kasasi kepada Pemohon/Termohon/Pembanding/Terbanding: isian tanggal',
    `tanggal_kirim_salinan_putusan` date DEFAULT NULL,
    `tanggal_cabut` date DEFAULT NULL,
    `dokumen_cabut_pihak` varchar(255) DEFAULT NULL,
    `dokumen_cabut_satker` varchar(255) DEFAULT NULL,
    `nomor_surat_pengantar_cabut` varchar(50) DEFAULT NULL,
    `tanggal_surat_pengantar_cabut` date DEFAULT NULL,
    `tidak_memenuhi_syarat` date DEFAULT NULL,
    `catatan_putusan_kasasi` longtext CHARACTER SET utf8mb4,
    `kondisi_pihak` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Apabila Y Pihak Masih Hidup Tapi Kalo T Pihak Wafat',
    `diedit_oleh` varchar(255) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `alur_perkara_id` (`alur_perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    KEY `pemohon_id` (`pemohon_id`),
    CONSTRAINT `perkara_kasasi_detil_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 19 DEFAULT CHARSET = latin1 COMMENT = 'Data Perkara Kasasi'

CREATE TABLE `perkara_keterangan_saksi` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) DEFAULT NULL,
    `sidang_id` bigint(20) DEFAULT NULL,
    `penanya_id` char(1) DEFAULT NULL COMMENT '1: Ketua Majelis; 2:Hakim Anggota 1; 3: Hakim Anggota 2; 4; Hakim Anggota :3; 5 Hakim Anggota 4',
    `saksi_id` int(11) DEFAULT NULL COMMENT 'refer perkara_pihak_5',
    `urutan_pertanyaan` int(11) DEFAULT NULL,
    `pertanyaan` longtext CHARACTER SET utf8mb4,
    `jawaban` longtext CHARACTER SET utf8mb4,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `perkara_id` (
        `perkara_id`,
        `sidang_id`,
        `saksi_id`,
        `urutan_pertanyaan`
    )
) ENGINE = InnoDB AUTO_INCREMENT = 237 DEFAULT CHARSET = latin1

CREATE TABLE `perkara_mediasi` (
    `mediasi_id` bigint(20) NOT NULL,
    `tahapan_id` tinyint(4) DEFAULT '10' COMMENT '10:pertama,20:banding,30:kasasi,40:pk',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key: (by system)',
    `general_id` bigint(20) DEFAULT '0',
    `jenis_mediasi` tinyint(1) DEFAULT '1' COMMENT '1:mediasi wajib, 2:mediasi sukarela 3:mediasi diluar pengadilan',
    `is_mediasi` tinyint(2) DEFAULT '1' COMMENT '1.Ya;-1.Tidak',
    `penetapan_penunjukan_mediator` date DEFAULT NULL COMMENT 'Tanggal Penetapan Penunjukan Mediator: isian tanggal',
    `nomor_sk_penetapan_mediator` varchar(50) DEFAULT '' COMMENT 'Nomor SK Penetapan Mediator: isian bebas',
    `sk_penetapan_mediator_dok` varchar(250) DEFAULT NULL COMMENT '(tidak digunakan lagi mulai 3.1)Dokumen SK Penetapan Mediator: form upload',
    `mediator_id` varchar(50) DEFAULT NULL COMMENT 'Id Mediator: dipisahkan dengan koma merujuk ke tabel mediator kolom id (by system)',
    `status_mediator` varchar(50) DEFAULT NULL COMMENT 'Status Mediator: merujuk ke tabel perkara_mediasi kolom status_mediator (by system)',
    `mediator_text` varchar(300) DEFAULT '' COMMENT 'Kode Status Mediator-Nama Mediator: merujuk ke tabel perkara_mediasi kolom status_mediator dan nama_mediator dipisahkan dengan tanda - (by system)',
    `penetapan_tanggal_mediasi` date DEFAULT NULL COMMENT '(tidak digunakan lagi mulai 3.1)Penetapan Tanggal Mediasi: isian tanggal',
    `dimulai_mediasi` date DEFAULT NULL COMMENT 'Tanggal Dimulai Mediasi: isian tanggal',
    `keputusan_mediasi` date DEFAULT NULL COMMENT 'Tanggal Keputusan Mediasi: isian tanggal',
    `hasil_mediasi` char(2) DEFAULT NULL COMMENT 'Hasil Mediasi: pilihan (Y1=Berhasil Dengan Kesepatakan; Y2:Berhasil Dengan Pencabutan, S=Berhasil Sebagian; T=Tidak Berhasil; D=Tidak dapat dilaksanakan)',
    `mediasi_berhasil` date DEFAULT NULL COMMENT '(tidak digunakan lagi mulai 3.1)Tanggal Mediasi Berhasil: diambil dari kolom keputusan_mediasi jika hasil_midiasi=Y berhasil (by system)',
    `tgl_kesepakatan_perdamaian` date DEFAULT NULL,
    `tgl_pengajuan_kesepakatan` date DEFAULT NULL,
    `isi_kesepakatan_perdamaian` longtext CHARACTER SET utf8mb4,
    `akta_perdamaian` date DEFAULT NULL COMMENT 'Tanggal Akta Perdamaian: isian bebas',
    `isi_akta_perdamaian` longtext CHARACTER SET utf8mb4,
    `isi_akta_perdamaian_dok` varchar(250) DEFAULT '' COMMENT 'Dokumen Isi Akta Perdamaian: form upload',
    `mediasi_gagal` date DEFAULT NULL COMMENT '(tidak digunakan lagi mulai 3.1)Tanggal Mediasi Gagal: diambil dari kolom keputusan_mediasi jika kolom hasil_mediasi=T (by system)',
    `catatan_mediasi` varchar(500) DEFAULT '' COMMENT 'Catatan Mediasi: isian bebas',
    `tgl_permohonan_uh` date DEFAULT NULL COMMENT 'Tanggal pihak mengajukan permohonan mediasi ke PN',
    `tgl_pemberitahuan_ke_ptma` date DEFAULT NULL COMMENT 'Tanggal PN memberitahukan ke PT/MA bahwa ada mediasi setelah pihak menyatakan banding',
    `tgl_laporan_mediator` date DEFAULT NULL COMMENT 'Tanggal mediator melaporkan bahwa mediasi sudah mendapatkan hasil',
    `tgl_kirim_kesepakatan_ke_ptma` date DEFAULT NULL COMMENT 'Tanggal PN mengirimkan hasil kesepakatan mediasi ke PT/MA',
    `diedit_oleh` varchar(30) DEFAULT '' COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT '' COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT '' COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`mediasi_id`),
    KEY `mediator_id` (`mediator_id`),
    KEY `mediasi_berhasil` (`mediasi_berhasil`),
    KEY `mediasi_gagal` (`mediasi_gagal`),
    KEY `keputusan_mediasi` (`keputusan_mediasi`),
    KEY `mediasi_id` (`mediasi_id`),
    KEY `perkara_mediasi_fk` (`perkara_id`),
    CONSTRAINT `perkara_mediasi_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Mediasi Perkara'

CREATE TABLE `perkara_mediator` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (generate by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara merujuk ke tabel perkara',
    `tanggal_penetapan` date DEFAULT NULL COMMENT 'Tanggal penetapan',
    `nomor_sk_penetapan` varchar(50) DEFAULT NULL COMMENT 'Nomor SK Penetapan: isian bebas',
    `urutan` int(11) unsigned DEFAULT '1' COMMENT 'urutan',
    `mediator_id` int(11) unsigned DEFAULT NULL COMMENT 'Id mediator merujuk ke tabel mediator',
    `status_mediator` char(1) DEFAULT NULL COMMENT 'Status Mediator: merujuk ke tabel mediator kolom status_mediator(by system)',
    `nama_mediator` varchar(50) DEFAULT NULL COMMENT 'Nama Mediator: merujuk ke tabel mediator kolom nama(by system)',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `tanggal_tidak_aktif` date DEFAULT NULL COMMENT 'Tanggal Tidak Aktif: isian tanggal',
    `keterangan` varchar(500) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `mediator_id` (`mediator_id`),
    KEY `status_mediator` (`status_mediator`),
    KEY `nama_mediator` (`nama_mediator`),
    CONSTRAINT `perkara_mediator_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_mediator_fk1` FOREIGN KEY (`mediator_id`) REFERENCES `mediator` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Mediator Perkara'

CREATE TABLE `perkara_panitera_pn` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key: (by system)',
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id',
    `tahapan_id` tinyint(4) NOT NULL DEFAULT '10' COMMENT 'Mengacu ke Table Tahapan',
    `tanggal_penetapan` date DEFAULT NULL COMMENT 'Tanggal Penetapan:isian tanggal',
    `nomor_sk_penetapan` varchar(50) DEFAULT NULL COMMENT 'Nomor SK Penetapan: isian bebas',
    `urutan` int(11) unsigned DEFAULT '1' COMMENT 'Urutan: (by system)',
    `panitera_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Panitera: merujuk ke tabel panitera_pn kolom id',
    `panitera_kode` varchar(20) DEFAULT NULL COMMENT 'Kode Panitera: merujuk ke tabel panitera_pn kolom kode (by system)',
    `panitera_nip` varchar(20) DEFAULT NULL COMMENT 'NIP Panitera: merujuk ke tabel panitera_pn kolom nip (by system)',
    `panitera_nama` varchar(50) DEFAULT NULL COMMENT 'Nama Panitera: merujuk ke tabel panitera_pn kolom nama (by system)',
    `diganti_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Panitera Pengganti: merujuk ke tabel panitera_pn kolom id',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `tanggal_tidak_aktif` date DEFAULT NULL COMMENT 'Tanggal Tidak Aktif: isian tanggal',
    `keterangan` varchar(500) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`perkara_id`),
    KEY `panitera_id` (`panitera_id`),
    KEY `panitera_nama` (`panitera_nama`),
    KEY `panitera_kode` (`panitera_kode`),
    KEY `aktif` (`aktif`),
    CONSTRAINT `perkara_panitera_pn_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_panitera_pn_fk1` FOREIGN KEY (`panitera_id`) REFERENCES `panitera_pn` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 10648 DEFAULT CHARSET = latin1 COMMENT = 'Data Panitera Pengganti Perkara di Pengadilan Negeri'

CREATE TABLE `perkara_pelaksanaan_relaas` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned NOT NULL,
    `sidang_id` int(11) NOT NULL COMMENT 'id dari kolom jenis_tahapan',
    `jurusita_id` int(11) NOT NULL COMMENT 'id table referensi_kolom_data_template',
    `pihak_id` bigint(20) DEFAULT NULL COMMENT 'Pihak yg dipanggil',
    `no_resi_pos` varchar(255) DEFAULT NULL,
    `tanggal_relaas` date DEFAULT NULL,
    `tanggal_jursit_pos` date DEFAULT NULL,
    `ket_temu` char(1) DEFAULT 'Y' COMMENT 'Y / T, E=Elektonik,S=surat tercatat,W=Web/Papan Pengumuman Pengadilan,P=papan pengumuman pemda,M=media massa cetak/elektornik,R=radio',
    `ket_hasil_relaas` longtext CHARACTER SET utf8mb4,
    `doc_relaas` varchar(255) DEFAULT NULL,
    `doc_resi` varchar(255) DEFAULT NULL,
    `status_pos` tinyint(1) DEFAULT NULL COMMENT '1. Berhasil 2.tidak berhasil (dikembalikan)',
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 13280 DEFAULT CHARSET = latin1

CREATE TABLE `perkara_penetapan` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key: (by system)',
    `jenis_acara` char(1) DEFAULT NULL COMMENT '1.Acara Cepat 2.Acara Biasa',
    `penetapan_majelis_hakim` date DEFAULT NULL COMMENT 'Tanggal Penetapan Majeis Hakim: isian tanggal',
    `nomor_sk_penetapan_majelis_hakim` varchar(50) DEFAULT '' COMMENT 'Nomor SK Penetapan Majelis Hakim: isian bebas',
    `sk_penetapan_majelis_hakim_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen SK Penetapan Majelis Hakim: form upload',
    `majelis_hakim_id` varchar(50) DEFAULT NULL COMMENT 'Id Hakim: dipisahkan dengan koma (by system)',
    `majelis_hakim_kode` varchar(100) DEFAULT NULL COMMENT 'Kode Hakim: dipisahkan oleh koma (by system)',
    `majelis_hakim_nama` varchar(500) DEFAULT NULL COMMENT 'Nama Hakim: dipisahkan dengan <br /> (by system)',
    `majelis_hakim_text` varchar(500) DEFAULT '' COMMENT 'View HTML Jabatan dan Nama Majelis Hakim (by system)',
    `penetapan_panitera_pengganti` date DEFAULT NULL COMMENT 'Tanggal Penetapan Panitera Pengganti: isian tanggal',
    `nomor_sk_penetapan_panitera_pengganti` varchar(50) DEFAULT NULL COMMENT 'Nomor SK penetapan Panitera Pengganti: isian bebas',
    `sk_penetapan_panitera_pengganti_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen SK Penetapan Panitera Pengganti: form upload',
    `panitera_pengganti_id` varchar(50) DEFAULT NULL COMMENT 'Id Panitera: dipisahkan dengan koma merujuk ke tabel perkara_panitera (by system)',
    `panitera_pengganti_text` varchar(500) DEFAULT '' COMMENT 'Nama Panitera Pengganti: dipisahkan dengan <br /> merujuk ke tabel perkara_panitera',
    `penetapan_jurusita` date DEFAULT NULL COMMENT 'Tanggal Penetapan Jurusita: isian tanggal',
    `nomor_sk_penetapan_jurusita` varchar(50) DEFAULT NULL COMMENT 'Nomor SK Penetapan Jurusita: isian bebas',
    `sk_penetapan_jurusita_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen SK Penetapan Jurusita: form upload',
    `jurusita_id` varchar(50) DEFAULT NULL COMMENT 'Id Jurusita: dipisahkan dengan koma yang merujuk ke tabel perkara_jurusita (by system)',
    `jurusita_text` varchar(500) DEFAULT '' COMMENT 'Nama Jurusita: dipisahkan dengan <br />\r\nmerujuk ke tabel perkara_jurusita(generate by system)',
    `penetapan_hari_sidang` date DEFAULT NULL COMMENT 'Tanggal Penetapan Hari Sidang: isian tanggal',
    `sidang_pertama` date DEFAULT NULL COMMENT 'Tanggal Sidang Pertama: merujuk ke tabel jadwal_sidang (by system)',
    `catatan_penetapan` longtext CHARACTER SET utf8mb4,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`perkara_id`),
    KEY `penetapan_majelis_hakim` (`penetapan_majelis_hakim`),
    KEY `majelis_hakim_nama` (`majelis_hakim_nama`),
    KEY `majelis_hakim_kode` (`majelis_hakim_kode`),
    KEY `penetapan_panitera_pengganti` (
        `penetapan_panitera_pengganti`
    ),
    KEY `panitera_pengganti_text` (`panitera_pengganti_text`),
    KEY `penetapan_jurusita` (`penetapan_jurusita`),
    KEY `penetapan_hari_sidang` (`penetapan_hari_sidang`),
    CONSTRAINT `perkara_penetapan_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Penetapan Perkara'

CREATE TABLE `perkara_penetapan_hari_sidang` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned NOT NULL,
    `tahapan_id` tinyint(4) NOT NULL DEFAULT '10' COMMENT 'Mengacu ke Table Tahapan',
    `jadwalsidang_id` bigint(20) unsigned NOT NULL COMMENT 'Mengacu ke tabel perkara_jadwal_sidang',
    `tanggal_penetapan` date NOT NULL,
    `tanggal_sidang` date NOT NULL,
    `keterangan` varchar(500) DEFAULT NULL,
    `diinput_oleh` varchar(30) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(30) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `tanggal_penetapan` (
        `tanggal_penetapan`,
        `tanggal_sidang`,
        `perkara_id`
    ),
    KEY `perkara_id` (`perkara_id`),
    KEY `tahapan_id` (`tahapan_id`),
    KEY `jadwalsidang_id` (`jadwalsidang_id`),
    CONSTRAINT `perkara_penetapan_hari_sidang_ibfk_1` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 12806 DEFAULT CHARSET = latin1

CREATE TABLE `perkara_pertimbangan_hukum` (
    `perkara_id` bigint(20) NOT NULL,
    `tanggal_pertimbangan_hukum` date DEFAULT NULL,
    `pertimbangan_hukum` longtext CHARACTER SET utf8mb4,
    `diinput_oleh` varchar(255) DEFAULT NULL,
    `diinput_tanggal` datetime DEFAULT NULL,
    `diperbaharui_oleh` varchar(255) DEFAULT NULL,
    `diperbaharui_tanggal` datetime DEFAULT NULL,
    PRIMARY KEY (`perkara_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `perkara_pihak1` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disi dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak kolom id',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `kondisi_pihak` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Apabila Y Pihak Masih Hidup Tapi Kalo T Pihak Wafat',
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: Isian bebas',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak1_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak1_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 14382 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Pertama(Penggugat/Pemohon/Penuntut)'

CREATE TABLE `perkara_pihak2` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Perkara: merujuk ke tabel perkara kolom perkara_id(by system)',
    `urutan` int(11) unsigned DEFAULT NULL COMMENT 'Urutan: disii dengan bilangan',
    `pihak_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id Pihak: merujuk ke tabel pihak',
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Id Jenis Pihak: merujuk ke tabel pihak kolom jenis_pihak_id(by system)',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: merujuk ke tabel pihak kolom nama(by system)',
    `alamat` varchar(500) DEFAULT NULL,
    `kondisi_pihak` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Apabila Y Pihak Masih Hidup Tapi Kalo T Pihak Wafat',
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `pangkat` varchar(100) DEFAULT NULL,
    `pangkat_id` tinyint(4) DEFAULT NULL,
    `nrp` varchar(50) DEFAULT NULL,
    `jabatan` varchar(100) DEFAULT NULL,
    `kesatuan` varchar(100) DEFAULT NULL,
    `ditahan_oleh_id` int(11) unsigned DEFAULT NULL COMMENT 'Ditahan Oleh (terakhir): merujuk ke tabel penahan_terdakwa (by system)',
    `status_penahanan_id` tinyint(4) unsigned DEFAULT NULL COMMENT 'Status Penahanan (terakhir): merujuk ke tabel status_penahanan kolom id(by system)',
    `jenis_tahanan_id` tinyint(4) unsigned DEFAULT NULL COMMENT 'Jenis Tahanan (terakhir): merujuk ke tabel jenis_tahanan kolom id (by system)',
    `ghaib` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Apakah pihak tidak diketahui alamatnya? 1(ya), 0(tidak)',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput oleh(by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput tanggal(by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaiki oleh(by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaiki tanggal(by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `perkara_id` (`perkara_id`),
    KEY `pihak_id` (`pihak_id`),
    CONSTRAINT `perkara_pihak2_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE,
    CONSTRAINT `perkara_pihak2_fk1` FOREIGN KEY (`pihak_id`) REFERENCES `pihak` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 6970 DEFAULT CHARSET = latin1 COMMENT = 'Data Pihak Kedua(Tergugat/Termohon/Terdakwa)'

CREATE TABLE `perkara_putusan` (
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `tanggal_putusan` date NOT NULL,
    `putusan_verstek` varchar(1) DEFAULT NULL COMMENT 'Putusan Verstek: pilihan Y=Ya; T=Tidak',
    `sumber_hukum_id` varchar(20) DEFAULT NULL COMMENT 'Diputus Dengan: pilihan (KUH Perdata,KUH Dagang, Adat, UU/PP)',
    `status_putusan_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Status Putusan: merujuk ke tabel status_putusan kolom id',
    `status_putusan_kode` varchar(20) DEFAULT NULL COMMENT 'Kode Status Putusan: merujuk ke tabel status putusan kolom kode (by system)',
    `status_putusan_nama` varchar(100) DEFAULT NULL COMMENT 'Nama Status Putusan: merujuk ke tabel status_putusan kolom nama (by system)',
    `status_putusan_text` varchar(5000) DEFAULT '' COMMENT 'Keterangan Putusan: (by system)',
    `tanggal_cabut` date DEFAULT NULL COMMENT 'Tanggal Cabut, jika status putusan dicabut(status_putusan_id=7)',
    `tanggal_gugur` date DEFAULT NULL COMMENT 'Tanggal Gugur: jika status putusan gugur(status_putusan_id=6)',
    `amar_putusan` longtext CHARACTER SET utf8mb4,
    `amar_putusan_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen Amar Putusan: form upload',
    `amar_putusan_anonimisasi_dok` varchar(250) DEFAULT NULL COMMENT 'Dokumen Amar Putusan Anonimisasi: form upload',
    `penetapan_hakim_pengawas` date DEFAULT NULL COMMENT 'Tanggal Penetapan Hakim Pengawas: isian tanggal',
    `nomor_penetapan_hakim_pengawas` varchar(50) DEFAULT NULL COMMENT 'Nomor Penetapan Hakim Pengawas',
    `hakim_pengawas_id` varchar(50) DEFAULT NULL COMMENT 'Id Hakim Pengawas: dipisahkan dengan koma',
    `pengurus_id` varchar(50) DEFAULT NULL COMMENT 'Id Pengurus: dipisahkan dengan koma',
    `tanggal_penetapan_kreditur` date DEFAULT NULL COMMENT 'Tanggal Penetapan Panitia Kreditur: isian tanggal',
    `panitia_kreditur` varchar(500) DEFAULT NULL COMMENT 'Panitia Kreditur: isian bebas',
    `kurator_id` varchar(50) DEFAULT NULL COMMENT 'Id Kurator: dipisahkan dengan koma',
    `tanggal_berita_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengumuman Dalam Berita Negara RI: isian tanggal',
    `nama_media_berita_putusan` varchar(250) DEFAULT NULL COMMENT 'Nama Media Berita: isian bebas',
    `tanggal_surat_kabar_putusan` date DEFAULT NULL COMMENT 'Tanggal Pengumuman Dalam Surat Kabar: isian tanggal',
    `nama_surat_kabar_putusan` varchar(250) DEFAULT NULL COMMENT 'Nama Surat Kabar: isian bebas',
    `tanggal_minutasi` date DEFAULT NULL COMMENT 'Tanggal Minutasi: isian tanggal',
    `pemberitahuan_putusan` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada para Pihak: isian tanggal',
    `pemberitahuan_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Penggugat/Pemohon/JPU: isian tanggal',
    `pemberitahuan_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Tergugat/Termohon/Terdakwa: isian tanggal',
    `pemberitahuan_putusan_pihak3` date DEFAULT NULL COMMENT 'Tanggal Pemberitahuan Putusan Kepada Pihak Intervensi: isian tanggal',
    `pemberitahuan_putusan_ankum` date DEFAULT NULL,
    `pemberitahuan_putusan_pepera` date DEFAULT NULL,
    `menerima_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal JPU menerima putusan: isian tanggal',
    `menerima_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Terdakwa Menerima Putusan: isian tanggal',
    `penerbitan_salinan_putusan` date DEFAULT NULL COMMENT 'Tanggal Penerbitan Salinan Putusan',
    `kirim_salinan_putusan_pihak1` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada JPU: isian tanggal',
    `kirim_salinan_putusan_pihak2` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Terdakwa: isian tanggal',
    `kirim_salinan_putusan_pihak3` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Pihak Intervensi: isian tanggal',
    `kirim_salinan_putusan_penyidik` date DEFAULT NULL COMMENT 'Tanggal Kirim Salian Putusan Kepada Penyidik: isian tanggal',
    `catatan_putusan` longtext CHARACTER SET utf8mb4,
    `nilai_ganti_kerugian` bigint(20) DEFAULT NULL,
    `tanggal_bht` date DEFAULT NULL,
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (
        `perkara_id`,
        `tanggal_putusan`
    ),
    KEY `tanggal_putusan` (`tanggal_putusan`),
    KEY `tanggal_cabut` (`tanggal_cabut`),
    KEY `tanggal_gugur` (`tanggal_gugur`),
    KEY `putusan_verstek` (`putusan_verstek`),
    KEY `status_putusan_id` (`status_putusan_id`),
    KEY `tanggal_minutasi` (`tanggal_minutasi`),
    CONSTRAINT `perkara_putusan_fk` FOREIGN KEY (`perkara_id`) REFERENCES `perkara` (`perkara_id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Data Putusan Perkara'

CREATE TABLE `perkara_putusan_pemberitahuan_putusan` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) unsigned NOT NULL COMMENT 'Primary Key: (by system)',
    `tahapan_id` int(10) unsigned NOT NULL DEFAULT '10',
    `putusan_akhir` tinyint(4) NOT NULL COMMENT '1:sela; 2:akhir',
    `pihak` tinyint(4) NOT NULL COMMENT '1:pihak1; 2:pihak2; 3:pihak3',
    `pihak_id` bigint(20) NOT NULL COMMENT 'id pihak dari masing2 tabel pihak',
    `tanggal_pemberitahuan_putusan` date DEFAULT NULL,
    `tanggal_menerima_putusan` date DEFAULT NULL,
    `tanggal_kirim_salinan_putusan` date DEFAULT NULL,
    `no_resi_pos` varchar(255) DEFAULT NULL,
    `tanggal_jursit_pos` date DEFAULT NULL,
    `ket_ketemu` char(1) DEFAULT NULL COMMENT 'Y / T, E=Elektonik,S=surat tercatat,W=Web/Papan Pengumuman Pengadilan,P=papan pengumuman pemda,M=media massa cetak/elektornik,R=radio',
    `edoc_resi` varchar(255) DEFAULT NULL,
    `edoc_pbt` varchar(255) DEFAULT NULL,
    `status_pos` tinyint(1) DEFAULT NULL COMMENT '1 Berhasil 2 tidak berhasil (kembali ke satker)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `unique` (
        `perkara_id`,
        `putusan_akhir`,
        `pihak`,
        `pihak_id`,
        `tahapan_id`
    )
) ENGINE = InnoDB AUTO_INCREMENT = 24014 DEFAULT CHARSET = latin1 COMMENT = 'PEmberitahuan Putusan ke Para Pihak'

CREATE TABLE `pihak` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `jenis_pihak_id` tinyint(1) unsigned DEFAULT NULL COMMENT 'Jenis Pihak: merujuk ke tabel jenis_pihak kolom id',
    `jenis_indentitas` varchar(50) DEFAULT NULL COMMENT 'Jenis identitas: diisi dengan KTP/SIM/PASPOR',
    `nomor_indentitas` varchar(50) DEFAULT NULL COMMENT 'Nomor Identitas: isian bebas',
    `nama` varchar(500) DEFAULT NULL COMMENT 'Nama: isian bebas',
    `tempat_lahir` varchar(50) DEFAULT NULL COMMENT 'Tempat Lahir: isian bebas',
    `tanggal_lahir` date DEFAULT NULL COMMENT 'Tanggal lahir: selisih tanggal lahir dengan tanggal hari ini tidak boleh kurang dari 5 tahun',
    `jenis_kelamin` varchar(1) DEFAULT NULL COMMENT 'Jenis Kelamin: L= Laki-laki, P=Perempuan',
    `golongan_darah` varchar(2) DEFAULT NULL COMMENT 'Golongan darah: A/B/AB/O',
    `alamat` varchar(500) DEFAULT NULL COMMENT 'Alamat: Isian bebas',
    `rtrw` varchar(20) DEFAULT NULL COMMENT 'RT/RW: isian bebas',
    `kelurahan` varchar(50) DEFAULT NULL COMMENT 'Kelurahan/Desa: isian bebas',
    `kecamatan` varchar(50) DEFAULT NULL COMMENT 'Kecamatan: Isian bebas',
    `kabupaten_id` int(11) unsigned DEFAULT NULL COMMENT 'Kabupaten/Kota: merujuk ke tabel kabupaten kolom id',
    `kabupaten` varchar(50) DEFAULT NULL COMMENT 'Kabupaten/Kota: merujuk ke tabel kabupaten kolom nama(by system)',
    `propinsi_id` int(11) unsigned DEFAULT NULL COMMENT 'Propinsi: merujuk ke tabel propinsi kolom id',
    `propinsi` varchar(50) DEFAULT NULL COMMENT 'Propinsi: merujuk ke tabel propinsi kolom nama(by system)',
    `telepon` varchar(50) DEFAULT NULL COMMENT 'Nomor telepon: isian bebas',
    `fax` varchar(50) DEFAULT NULL COMMENT 'Nomor Fax: isian bebas',
    `email` varchar(50) DEFAULT NULL COMMENT 'Alamat email: isan format email',
    `agama_id` int(11) unsigned DEFAULT NULL COMMENT 'Agama: merujuk ke tabel agama kolom id',
    `agama_nama` varchar(50) DEFAULT NULL COMMENT 'Nama Agama: merujuk ke tabel agama kolom nama(by system)',
    `status_kawin` char(1) DEFAULT NULL COMMENT 'Statu Kawin: diisi dengan Kawin/Belum Kawin',
    `pekerjaan` varchar(255) DEFAULT NULL COMMENT 'Pekerjaan: isian bebas',
    `pendidikan_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Tingkat Pendidikan Terakhir: merujuk ke tabel tingkat_pendidikan kolom id',
    `pendidikan` varchar(50) DEFAULT NULL COMMENT 'Pendidikan terakhir: merujuk ke tabel pendidikan kolom kode',
    `warga_negara_id` int(11) unsigned DEFAULT NULL COMMENT 'Id Negara: merujuk ke tabel negara kolom id',
    `warga_negara` varchar(50) DEFAULT NULL COMMENT 'Warga Negara: merujuk ke tabel negara kolom nama (by system)',
    `nama_ayah` varchar(50) DEFAULT NULL COMMENT 'Nama Ayah: isian bebas',
    `nama_ibu` varchar(50) DEFAULT NULL COMMENT 'Nama ibu: isian bebas',
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `foto` blob,
    `difabel` char(1) NOT NULL DEFAULT 'T' COMMENT 'Y=Ya, T = Tidak',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `nama` (`nama`),
    KEY `jenis_pihak_id` (`jenis_pihak_id`),
    KEY `kabupaten_id` (`kabupaten_id`),
    KEY `agama_id` (`agama_id`),
    KEY `warga_negara_id` (`warga_negara_id`),
    KEY `pendidikan_id` (`pendidikan_id`),
    CONSTRAINT `pihak_fk` FOREIGN KEY (`jenis_pihak_id`) REFERENCES `jenis_pihak` (`id`),
    CONSTRAINT `pihak_fk1` FOREIGN KEY (`kabupaten_id`) REFERENCES `kabupaten` (`id`),
    CONSTRAINT `pihak_fk2` FOREIGN KEY (`agama_id`) REFERENCES `agama` (`id`),
    CONSTRAINT `pihak_fk3` FOREIGN KEY (`warga_negara_id`) REFERENCES `negara` (`id`),
    CONSTRAINT `pihak_fk4` FOREIGN KEY (`pendidikan_id`) REFERENCES `tingkat_pendidikan` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 40488 DEFAULT CHARSET = latin1 AVG_ROW_LENGTH = 537 COMMENT = 'Data Para Pihak'

CREATE TABLE `proses_alur_perkara` (
    `id` int(11) DEFAULT NULL,
    `alur_perkara_id` int(11) unsigned NOT NULL COMMENT 'Jenis proses: merujuk ke tabel jenis_proses kolom id',
    `tahapan_id` int(11) unsigned NOT NULL COMMENT 'Id tahapan prose merujuk ke tabel tahapan_proses',
    `tahapan_nama` varchar(50) DEFAULT NULL COMMENT 'Nama Tahapan Proses: merujuk ke tabel tahapan_proses kolom nama (by system)',
    `proses_id` int(11) unsigned NOT NULL COMMENT 'id Proses: merujuk ke tabel proses kolom id',
    `proses_nama` varchar(250) DEFAULT NULL COMMENT 'Nama Proses: merujuk ke tabel proses kolom nama (by system)',
    `batas_waktu` int(11) unsigned DEFAULT NULL COMMENT 'Batas waktu maksimum proses (satuan hari)',
    `satuan` varchar(50) DEFAULT NULL COMMENT 'Satuan: pilihan (Hari Kerja, Hari Kalender, Bulan) ',
    `dari_proses_id` int(11) unsigned DEFAULT NULL COMMENT 'Dari Id Proses: merujuk ke tabel proses kolom id',
    `nama_tabel_dari` varchar(64) DEFAULT NULL COMMENT 'Nama Tabel Dari: merujuk ke tabel proses kolom nama_tabel dengan id=dari_proses_id (by system)',
    `nama_kolom_dari` varchar(64) DEFAULT NULL COMMENT 'Nama Kolom Dari: merujuk ke tabel proses kolom nama_kolom dengan id=dari_proses_id (by system)',
    `nama_tabel_ke` varchar(64) DEFAULT NULL COMMENT 'Nama Tabel Ke: merujuk ke tabel proses kolom nama_tabel dengan id=proses_id (by system)',
    `nama_kolom_ke` varchar(64) DEFAULT NULL COMMENT 'Nama Kolom Ke: merujuk ke tabel proses kolom nama_kolom dengan id=proses_id (by system)',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `reminder` tinyint(1) unsigned NOT NULL DEFAULT '0',
    `keterangan` varchar(255) DEFAULT NULL COMMENT 'Keterangan: isian bebas',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (
        `alur_perkara_id`,
        `tahapan_id`,
        `proses_id`
    ),
    UNIQUE KEY `alur_perkara_id` (
        `alur_perkara_id`,
        `tahapan_id`,
        `proses_id`
    ),
    UNIQUE KEY `alur_perkara_id_2` (
        `alur_perkara_id`,
        `tahapan_id`,
        `proses_id`
    ),
    KEY `tahapan_id` (`tahapan_id`),
    KEY `nama` (`proses_nama`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Referensi Proses Alur Perkara'

CREATE TABLE `status_pihak` (
    `alur_perkara_id` int(11) unsigned NOT NULL,
    `tahapan_id` int(11) unsigned NOT NULL COMMENT 'Id Tahapan: 1= Tingkat Pertama; 2=Banding; 3=Kasasi; 4;PK; 5=Eksekusi; 6=Grasi',
    `pihak_ke` tinyint(1) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `kode` varchar(20) DEFAULT NULL COMMENT 'Kode Status Putusan: isaian bebas',
    `nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Nama Status Putusan: isaian bebas',
    `keterangan` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Keterangan: isaian bebas',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `urutan` int(11) unsigned NOT NULL COMMENT 'Urutan berdasarkan jenis_proses_id',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (
        `alur_perkara_id`,
        `tahapan_id`,
        `pihak_ke`
    ),
    KEY `nama` (`nama`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Referensi Status Para Pihak'

CREATE TABLE `status_putusan` (
    `id` int(11) unsigned NOT NULL COMMENT 'Primary key (by system)',
    `jenis_perkara_id` int(11) unsigned NOT NULL COMMENT 'Id Jenis Perkara: merujuk ke tabel jenis_perkara kolom id',
    `kode` varchar(20) DEFAULT NULL COMMENT 'Kode Status Putusan: isaian bebas',
    `nama` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Nama Status Putusan: isaian bebas',
    `keterangan` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'Keterangan: isaian bebas',
    `aktif` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Status Aktif: pilihan Y=Ya; T=Tidak',
    `urutan` int(11) unsigned NOT NULL COMMENT 'Urutan berdasarkan jenis_proses_id',
    `satuan` tinyint(4) DEFAULT NULL COMMENT '1.Time/Hari,2.Nominal/Rupiah,3.checkbox,4.Uraian;',
    `jenis_pengadilan` tinyint(1) NOT NULL DEFAULT '1',
    `diedit_oleh` varchar(30) DEFAULT NULL COMMENT 'Diedit Oleh: (by system)',
    `diedit_tanggal` datetime DEFAULT NULL COMMENT 'Diedit Tanggal: (by system)',
    `diinput_oleh` varchar(30) DEFAULT NULL COMMENT 'Diinput Oleh: (by system)',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'Diinput Tanggal: (by system)',
    `diperbaharui_oleh` varchar(30) DEFAULT NULL COMMENT 'Diperbaharui Oleh: (by system)',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'Diperbaharui Tanggal: (by system)',
    PRIMARY KEY (`id`),
    KEY `perkara_id` (`jenis_perkara_id`),
    KEY `nama` (`nama`),
    KEY `kode` (`kode`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COMMENT = 'Referensi Status Putusan'

CREATE TABLE `ecourt_antrian_pendaftaran` (
    `antrian_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `efiling_id` bigint(20) unsigned NOT NULL,
    `pendaftaran_id` bigint(20) unsigned DEFAULT NULL,
    `tahapan_id` int(10) unsigned NOT NULL DEFAULT '10',
    `status_antrian` tinyint(1) unsigned NOT NULL DEFAULT '0',
    `diinput_tanggal` datetime NOT NULL,
    `diperbaharui_tanggal` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`antrian_id`),
    UNIQUE KEY `efiling_id` (
        `efiling_id`,
        `pendaftaran_id`,
        `tahapan_id`
    ),
    KEY `status_antrian` (`status_antrian`)
) ENGINE = InnoDB AUTO_INCREMENT = 1808 DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_biaya` (
    `id` bigint(1) unsigned NOT NULL,
    `flag` tinyint(1) unsigned NOT NULL DEFAULT '0',
    `flag_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `flag` (`flag`),
    KEY `flag_delete` (`flag_delete`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_jadwal_sidang` (
    `id` int(11) unsigned NOT NULL,
    `flag` int(10) unsigned NOT NULL DEFAULT '0',
    `flag_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `flag` (`flag`),
    KEY `flag_delete` (`flag_delete`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_kuasa_hukum` (
    `efiling_id` bigint(20) unsigned NOT NULL,
    `pendaftaran_id` bigint(20) unsigned NOT NULL DEFAULT '0',
    `ecourt_pengacara_id` bigint(20) unsigned NOT NULL,
    `ecourt_pihak_id` bigint(20) unsigned NOT NULL,
    `tahapan_id` bigint(20) unsigned NOT NULL,
    `status_pihak` int(11) unsigned NOT NULL,
    `aktif` char(1) NOT NULL DEFAULT 'Y',
    PRIMARY KEY (
        `efiling_id`,
        `pendaftaran_id`,
        `ecourt_pengacara_id`,
        `ecourt_pihak_id`
    )
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_perkara_hakim` (
    `id` int(11) unsigned NOT NULL,
    `flag` int(10) unsigned NOT NULL DEFAULT '0',
    `flag_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `flag` (`flag`),
    KEY `flag_delete` (`flag_delete`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_perkara_jurusita` (
    `id` int(11) unsigned NOT NULL,
    `flag` int(10) unsigned NOT NULL DEFAULT '0',
    `flag_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `flag` (`flag`),
    KEY `flag_delete` (`flag_delete`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_perkara_panitera` (
    `id` int(11) unsigned NOT NULL,
    `flag` int(10) unsigned NOT NULL DEFAULT '0',
    `flag_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `flag` (`flag`),
    KEY `flag_delete` (`flag_delete`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_perkara_panitera` (
    `id` int(11) unsigned NOT NULL,
    `flag` int(10) unsigned NOT NULL DEFAULT '0',
    `flag_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `flag` (`flag`),
    KEY `flag_delete` (`flag_delete`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_pihak` (
    `ecourt_pihak_id` bigint(20) unsigned NOT NULL,
    `efiling_id` bigint(20) unsigned NOT NULL,
    `sipp_pihak_id` bigint(20) unsigned NOT NULL,
    `pihak_id` bigint(20) unsigned NOT NULL COMMENT 'Pihak ID hasil mapping awal (asli)',
    `status_pihak_id` bigint(20) unsigned NOT NULL,
    `verifikasi_pihak` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'pencocokan pihak ecourt dan sipp',
    PRIMARY KEY (
        `ecourt_pihak_id`,
        `efiling_id`
    ),
    KEY `efiling_id` (`efiling_id`),
    KEY `sipp_pihak_id` (`sipp_pihak_id`),
    KEY `status_pihak_id` (`status_pihak_id`),
    KEY `verifikasi_pihak` (`verifikasi_pihak`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_prodeo` (
    `id` bigint(20) NOT NULL,
    `efiling_id` bigint(20) DEFAULT NULL,
    `jenis_prodeo` tinyint(1) DEFAULT NULL COMMENT '2 : DIPA 3 : Murni',
    `status` tinyint(1) DEFAULT NULL COMMENT '0 : Menunggu Verifikasi, 1 : Diterima, 2 : Ditolak',
    `document` varchar(500) DEFAULT NULL COMMENT 'Berisi link dokumen SKTM dari eCourt',
    `document_penetapan` varchar(500) DEFAULT NULL COMMENT 'Berisi link dokumen penetapan persetujuan prodeo',
    `keterangan` varchar(500) DEFAULT NULL COMMENT 'Keterangan jika prodeo ditolak',
    `info` longtext COMMENT 'Berisi data nomor pendaftaran, tanggal permohonan dan alur perkara nama',
    `biaya_prodeo` int(11) DEFAULT NULL COMMENT 'Berisi Biaya Prodeo Yang Dianggarkan Satker',
    `diinput_oleh` varchar(50) DEFAULT NULL COMMENT 'diinput oleh user dari ecourt',
    `diinput_tanggal` datetime DEFAULT NULL COMMENT 'diinput tanggal dari data ecourt',
    `diperbaharui_oleh` varchar(50) DEFAULT NULL COMMENT 'diupdate oleh verifikator di sipp',
    `diperbaharui_tanggal` datetime DEFAULT NULL COMMENT 'diupdate oleh verifikator di sipp',
    PRIMARY KEY (`id`),
    KEY `efiling_id` (`efiling_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `ecourt_putusan` (
    `perkara_id` bigint(1) unsigned NOT NULL,
    `flag` tinyint(1) unsigned NOT NULL DEFAULT '0',
    `flag_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`perkara_id`),
    KEY `flag` (`flag`),
    KEY `flag_delete` (`flag_delete`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1

CREATE TABLE `dirput_antrian` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) NOT NULL COMMENT 'sesuai dengan sipp',
    `status` tinyint(1) DEFAULT NULL COMMENT '1 = berhasil, 0 = belum upload, -1 = error',
    `last_tried` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'menunjukkan waktu percobaan terakhir',
    `keterangan` varchar(500) DEFAULT NULL COMMENT 'sebagai log transaksi',
    `tgl_masuk` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 12716 DEFAULT CHARSET = latin1

CREATE TABLE `dirput_dokumen` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `perkara_id` bigint(20) NOT NULL,
    `dokumen_ref_id` bigint(20) NOT NULL,
    `filename` varchar(255) NOT NULL,
    `path_filename` varchar(355) NOT NULL,
    `created_by` varchar(255) NOT NULL,
    `created_date` date NOT NULL,
    `updated_by` varchar(255) DEFAULT NULL,
    `updated_date` date DEFAULT NULL,
    `pihak_detil_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'merujuk ke tabel banding_detil, kasasi_detil, pk_detil pada kolom id',
    `keterangan` varchar(255) DEFAULT NULL,
    `flag_sync` tinyint(1) DEFAULT NULL COMMENT 'penanda antrian sudah terupload atau belum',
    `pengajuan_id` tinyint(1) unsigned NOT NULL COMMENT '1 = tidak diajukan, 2 = banding, 3 = kasasi, 4 = pk, 5 = grasi',
    `published` tinyint(1) DEFAULT '0' COMMENT '0 = tidak dipublished, 1 = di published',
    `link_dirput` varchar(255) DEFAULT NULL,
    PRIMARY KEY (
        `perkara_id`,
        `dokumen_ref_id`,
        `pihak_detil_id`,
        `pengajuan_id`
    ),
    KEY `id` (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 24771 DEFAULT CHARSET = latin1

CREATE TABLE `dirput_perkara` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id perkara di dirput',
    `perkara_id` bigint(20) DEFAULT NULL COMMENT 'perkara id sesuai sipp',
    `putusan_id` varchar(100) NOT NULL COMMENT 'putusan id didapat dari tarik data dirput',
    `nomor_perkara` varchar(50) NOT NULL COMMENT 'no perkara sesuai sipp',
    `pengajuan_id` tinyint(1) unsigned DEFAULT NULL COMMENT '1 = tdk mengajukan, 2 = banding, 3 = kasasi, 4 = pk, 5 = grasi',
    `nomor_perkara_key` varchar(255) DEFAULT NULL COMMENT 'nomor perkara dari dirput',
    PRIMARY KEY (`id`),
    UNIQUE KEY `nomor_perkara` (`nomor_perkara`),
    UNIQUE KEY `putusan_id` (`putusan_id`),
    UNIQUE KEY `perkara_id` (`perkara_id`)
) ENGINE = InnoDB AUTO_INCREMENT = 147696 DEFAULT CHARSET = latin1
